feature: make KMS prefix an env var

diff --git a/src/compose/production/django/celery/flower/start b/src/compose/production/django/celery/flower/start
--- a/src/compose/production/django/celery/flower/start
+++ b/src/compose/production/django/celery/flower/start
@@ -3,22 +3,26 @@
 set -o errexit
 set -o nounset
 
-CELERY_FLOWER_USER="${CELERY_FLOWER_USER:-"admin"}"
+CELERY_FLOWER_USER="${CELERY_FLOWER_USER:-""}"
+CELERY_FLOWER_PASSWORD="${CELERY_FLOWER_PASSWORD:-""}"
 CELERY_FLOWER_PASSWORD_ENCRYPTED="${CELERY_FLOWER_PASSWORD_ENCRYPTED:-"false"}"
 
- if [[ "${CELERY_FLOWER_PASSWORD_ENCRYPTED}" == "true" ]]; then
-     echo "${CELERY_FLOWER_PASSWORD#"kms+base64:"}" | base64 -d > "/tmp/cipher.blob"
-     CELERY_FLOWER_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d )"
+KMS_PREFIX="${KMS_PREFIX:-"kms+base64:"}"
 
-     if [[ -z "${CELERY_FLOWER_PASSWORD}" ]]; then
-         echo "Celery Password was supposed to be encrypted but we couldn't decrypt it"
-         exit 255
-     fi
- fi
+if [[ -n "${CELERY_FLOWER_USER}" && -n "${CELERY_FLOWER_PASSWORD}" ]]; then
+    if [[ "${CELERY_FLOWER_PASSWORD_ENCRYPTED}" == "true" ]]; then
+        echo "${CELERY_FLOWER_PASSWORD#${KMS_PREFIX}}" | base64 -d > "/tmp/cipher.blob"
+        CELERY_FLOWER_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d )"
 
-export FLOWER_BASIC_AUTH="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
+        if [[ -z "${CELERY_FLOWER_PASSWORD}" ]]; then
+            echo "Celery Password was supposed to be encrypted but we couldn't decrypt it"
+            exit 255
+        fi
+    fi
+
+    export FLOWER_BASIC_AUTH="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
+fi
 
 celery flower \
     --app=chambers_app.taskapp \
-    --broker="${CELERY_BROKER_URL}" \
-    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
+    --broker="${CELERY_BROKER_URL}"
